ARG CLIENT_IMAGE
ARG OSCRIPT_IMAGE=oscript:oscript

FROM ${CLIENT_IMAGE} AS base

FROM ${OSCRIPT_IMAGE}
LABEL org.opencontainers.image.authors="Anatolii Sereda <3011745+anatox@users.noreply.github.com>"

ARG gitsync_ver=3.7.3

COPY --from=base /opt /opt

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt/lists,sharing=locked <<'EOF'
  set -eux
  DEBIAN_FRONTEND=noninteractive apt-get install -y -o=Dpkg::Use-Pty=0 --no-install-recommends \
    dbus-x11
  locale-gen ru_RU.UTF-8
EOF
ENV LANG=ru_RU.UTF-8

RUN <<'EOF'
  set -eux
  opm install gitsync@${gitsync_ver}
EOF

ENTRYPOINT ["gitsync"]
CMD ["usage"]
