ARG BASE_IMAGE=localhost/onec-server:local

FROM ${BASE_IMAGE}
LABEL org.opencontainers.image.authors="Anatolii Sereda <3011745+anatox@users.noreply.github.com>"

ARG gui_ver=1.0.1
ARG gui_url=https://nuk-svk.ru/uploads/rac-gui

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt/lists,sharing=locked <<'EOF'
  set -eux
  apt-get update -qq
  DEBIAN_FRONTEND=noninteractive apt-get install -y -o=Dpkg::Use-Pty=0 --no-install-recommends \
    tk8.6 \
    tcl8.6 \
    tk \
    ca-certificates \
    wget
  wget $gui_url/rac_gui-"$gui_ver".deb
  dpkg -x rac_gui-$gui_ver.deb /tmp
  mv /tmp/usr/share/rac_gui /usr/share
  mv /tmp/usr/bin/racgui /usr/bin
  rm -f rac_gui-$gui_ver.deb
EOF

CMD ["racgui"]
