ARG BASE_IMAGE=localhost/oscript:local

FROM ${BASE_IMAGE}
LABEL org.opencontainers.image.authors="Anatolii Sereda <3011745+anatox@users.noreply.github.com>"

RUN <<'EOF'
  set -eux
  opm install vanessa-runner
  opm install packman
  opm install gitsync
  opm install deployka
  opm install add
  opm install vanessa-automation
  # https://github.com/silverbulleters/vanessa-runner/pull/301
  sed -i 's/#Использовать JSON/#Использовать json/g' \
    /usr/share/oscript/lib/vanessa-runner/src/Модули/ГенерацияОтчетов.os
EOF
