ARG BASE_IMAGE=ubuntu:26.04

FROM ${BASE_IMAGE}

LABEL org.opencontainers.image.authors="Anatolii Sereda <3011745+anatox@users.noreply.github.com>"
LABEL author="Iosif Pravets"

ARG EXECUTOR_VERSION

WORKDIR /tmp

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt/lists,sharing=locked <<'EOF'
  set -eux
  apt-get update -qq
  DEBIAN_FRONTEND=noninteractive apt-get install -y -o=Dpkg::Use-Pty=0 --no-install-recommends \
    locales \
    ca-certificates \
    curl \
    unzip
  locale-gen ru_RU.UTF-8
EOF

ENV LANG=ru_RU.UTF-8

# Install Executor (используем BuildKit secret)
RUN --mount=type=secret,id=secrets_env \
    --mount=type=cache,target=/var/cache/executor,sharing=locked <<'EOF'
  set -eux
  set -a; . /run/secrets/secrets_env >/dev/null 2>&1; set +a
  zip_path="/var/cache/executor/executor-${EXECUTOR_VERSION}.zip"
  if [ -f "$zip_path" ]; then
    cp "$zip_path" executor.zip
  else
    curl -sSL --fail \
      -H "X-Developer-1c-Api:${DEV1C_EXECUTOR_API_KEY}" \
      -o executor.zip \
      https://developer.1c.ru/applications/Console/api/v1/download/executor/${EXECUTOR_VERSION}/linux
    cp executor.zip "$zip_path"
  fi
  unzip executor.zip
  rm executor.zip
  mkdir -p /opt/1C/executor
  cp -R * /opt/1C/executor
# cleanup
  rm -rf /tmp/*
  apt purge -y unzip
EOF

ENV PATH="/opt/1C/executor:$PATH"
ENTRYPOINT ["/opt/1C/executor/executor"]