ARG BASE_IMAGE=oscript:oscript

FROM ${BASE_IMAGE}
LABEL org.opencontainers.image.authors="Anatolii Sereda <3011745+anatox@users.noreply.github.com>"

ARG runner_ver=1.7.0

RUN <<'EOF'
  set -eux
  opm install vanessa-runner@$runner_ver
  sed -i 's/#Использовать JSON/#Использовать json/g' \
    /usr/share/oscript/lib/vanessa-runner/src/Модули/ГенерацияОтчетов.os
EOF

ENTRYPOINT ["runner"]
CMD ["help"]
