group "default" {
  targets = [
    "base-jenkins-agent-k8s",
    "base-jenkins-agent-swarm",
    "client",
    "client-oscript",
    "client-s6",
    "client-vnc",
    "client-vnc-oscript",
    "client-vnc-oscript-jdk",
    "coverage-agent-k8s",
    "coverage-agent-swarm",
    "crs",
    "crs-apache",
    "edt",
    "edt-agent-k8s",
    "edt-agent-swarm",
    "edt-s6",
    "executor",
    "gitsync",
    "installer",
    "oscript",
    "oscript-agent-k8s",
    "oscript-agent-swarm",
    "oscript-jdk",
    "oscript-jdk-s6",
    "server",
    "thin-client",
    "test-utils",
    "vanessa-runner",
  ]
}

group "publish" {
  targets = [
    "base-jenkins-agent-k8s",
    "base-jenkins-agent-swarm",
    "client",
    "client-vnc",
    "coverage-agent-k8s",
    "coverage-agent-swarm",
    "crs",
    "crs-apache",
    "edt",
    "edt-agent-k8s",
    "edt-agent-swarm",
    "executor",
    "gitsync",
    "installer",
    "oscript",
    "oscript-agent-k8s",
    "oscript-agent-swarm",
    "server",
    "thin-client",
    "vanessa-runner",
  ]
}
