name: Build oscript-swarm-agent

on:
  workflow_call:
    inputs:
      build_enabled:
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      publish:
        type: boolean
        default: false

permissions:
  contents: read
  packages: write

jobs:
  build:
    if: github.event_name == 'workflow_dispatch' || inputs.build_enabled
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/pre-build

      - name: Build image (oscript-jdk)
        id: build-oscript-jdk
        uses: ./.github/actions/build-image
        with:
          image_name: oscript-jdk
          image_version: latest
          image_desc: OneScript + JDK
          containerfile: oscript/Containerfile
          build_args: |
            BASE_IMAGE=eclipse-temurin
            BASE_TAG=17
          is_default_branch: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image (oscript-jdk-s6)
        id: build-oscript-jdk-s6
        uses: ./.github/actions/build-image
        with:
          image_name: oscript-jdk-s6
          image_version: latest
          image_desc: OneScript + JDK + s6-overlay
          containerfile: s6-overlay/Containerfile
          build_args: |
            BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/${{ steps.build-oscript-jdk.outputs.image }}
            BASE_TAG=latest
          is_default_branch: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image (oscript-agent)
        id: build-oscript-agent
        uses: ./.github/actions/build-image
        with:
          image_name: oscript-agent
          image_version: latest
          image_desc: OneScript swarm agent
          containerfile: swarm-jenkins-agent/Containerfile
          build_args: |
            BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/${{ steps.build-oscript-jdk-s6.outputs.image }}
            BASE_TAG=latest
          is_default_branch: ${{ github.ref == 'refs/heads/main' }}
          publish: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.publish) || 'false' }}
