name: Build server

run-name: ${{ github.ref_type == 'tag' && format('Build {0}', github.ref_name) || 'Build server' }}

on:
  push:
    tags:
      - 'packages/server/v*'
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      platform_version:
        description: 1C:Enterprise platform version
        type: string
        default: '8.5.1.1343'
      nls_enabled:
        type: boolean
        default: false
      publish:
        type: boolean
        default: false

permissions:
  contents: write
  packages: write

jobs:
  build:
    if: github.event_name != 'pull_request' || vars.BUILD_SERVER != 'false'
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: ${{ github.ref_type == 'tag' && '0' || '1' }}

      - id: pre-build
        uses: ./.github/actions/pre-build
        with:
          component: server

      - id: build-installer
        uses: ./.github/actions/build-installer
        with:
          is_default_branch: ${{ steps.pre-build.outputs.is_default_branch == 'true' }}

      - name: Build image (onec-server)
        id: build-server
        uses: ./.github/actions/build-image
        with:
          image_name: onec-server
          image_version: ${{ steps.pre-build.outputs.image_tag || inputs.platform_version }}
          image_title: 1C:Enterprise server
          containerfile: server/Containerfile
          build_args: |
            ONEC_VERSION=${{ steps.pre-build.outputs.version || inputs.platform_version }}
            NLS_ENABLED=${{ inputs.nls_enabled || vars.NLS_ENABLED || false }}
            INSTALLER_IMAGE=${{ steps.build-installer.outputs.image-with-tag }}
          secrets: |
            onec_username=${{ secrets.ONEC_USERNAME }}
            onec_password=${{ secrets.ONEC_PASSWORD }}
          is_default_branch: ${{ steps.pre-build.outputs.is_default_branch == 'true' }}
          publish: ${{ github.ref_type == 'tag' || (github.event_name == 'workflow_dispatch' && inputs.publish) }}
          registry_url: ${{ vars.CONTAINER_REGISTRY_URL }}
          registry_username: ${{ vars.CONTAINER_REGISTRY_USERNAME }}
          registry_password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
