name: Build edt-k8s-agent

on:
  workflow_call:
    inputs:
      build_enabled:
        type: boolean
        default: true
    secrets:
      ONEC_USERNAME:
        required: true
      ONEC_PASSWORD:
        required: true
  workflow_dispatch:
    inputs:
      publish:
        type: boolean
        default: false

permissions:
  contents: read
  packages: write

jobs:
  build:
    if: github.event_name == 'workflow_dispatch' || inputs.build_enabled
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/pre-build

      - id: build-edt
        uses: ./.github/actions/build-edt
        with:
          EDT_VERSION: '2025.2.6'
          OPENJDK_VERSION: '17'
          ONEC_USERNAME: ${{ secrets.ONEC_USERNAME }}
          ONEC_PASSWORD: ${{ secrets.ONEC_PASSWORD }}
          is_default_branch: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image (edt-s6)
        id: build-edt-s6
        uses: ./.github/actions/build-image
        with:
          image_name: edt-s6
          image_version: '2025.2.6'
          image_desc: EDT + s6-overlay
          containerfile: s6-overlay/Containerfile
          build_args: |
            BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/${{ steps.build-edt.outputs.image }}
            BASE_TAG=2025.2.6
          is_default_branch: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image (edt-agent)
        id: build-edt-agent
        uses: ./.github/actions/build-image
        with:
          image_name: edt-agent
          image_version: '2025.2.6'
          image_desc: EDT k8s agent
          containerfile: k8s-jenkins-agent/Containerfile
          build_args: |
            BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/${{ steps.build-edt-s6.outputs.image }}
            BASE_TAG=2025.2.6
          is_default_branch: ${{ github.ref == 'refs/heads/main' }}
          publish: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.publish) || 'false' }}
