ARG BASE_IMAGE=oscript:oscript

FROM ${BASE_IMAGE}
LABEL org.opencontainers.image.authors="Anatolii Sereda <3011745+anatox@users.noreply.github.com>"

ARG YARD_VERSION=1.9.2

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt/lists,sharing=locked <<'EOF'
  set -euxo pipefail
  apt-get update -qq
  DEBIAN_FRONTEND=noninteractive apt-get install -y -o=Dpkg::Use-Pty=0 --no-install-recommends \
    7zip
  opm install \
    yard@${YARD_VERSION}
EOF

# Копируем скрипты установки
COPY --chmod=755 scripts/installer /opt/onec-installer
ENV PATH="$PATH:/opt/onec-installer/bin"
